apiVersion: apps/v1
kind: Deployment
metadata:
  name: peopleweb
  labels:
    app: peopleweb
spec:
  replicas: 1
  template:
    metadata:
      name: peopleweb
      labels:
        app: peopleweb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: peopleweb
        image: shayne.azurecr.io/peoplewebapp-core:latest
        env:
        - name: "SERVICE_URL"
          value: "peoplesvc"
        resources:
          # limits:
          #   cpu: 1
          #   memory: 800M
          # requests:
          #   cpu: 1
          #   memory: 300M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: peopleweb
---
apiVersion: v1
kind: Service
metadata:
  name: peopleweb
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: peopleweb